server.port: 7112

solon.app:
#  namespace: test  #也可以写在下面
  group: demo
  name: helloapi    #发现服务使用的应用名（在Demo，将被NimaClient引用）


solon.cloud.nacos:
  server: localhost:8848   #nacos服务地址
  namespace: test


solon.logging.logger:
  "com.alibaba.nacos":
    level: ERROR