solon.app:
  name: demoapp
  group: demo

solon.logging.appender:
  console:
    level: TRACE
    pattern: "%highlight{%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} #%5X{pid} [-%t][*%X{traceId}]%tags[%logger{20}]:} %msg%n"
  file:
    name: "logs/demo2"
    level: INFO
