solon.app:
  name: demoapp
  group: demo

solon.output.meta: 1

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"


test.db1:
  schema: rock
  jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: 123456
