solon.app:
  name: demoapp
  group: demo

solon.output.meta: 1

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"


solon.dataSources:
  db1!:
    class: "com.zaxxer.hikari.HikariDataSource"
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

dbvisitor:
  db1:   # 对应的数据源名称
    mapperLocations: classpath:demo4072/dso/mapper/*.xml
    mapperPackages: demo4072.dso.mapper.*
    dialect: mysql
