version: "3"

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - pub-network
    restart: always
    environment:
      # 设置 Kafka 节点的 ID 为 1。在 Kafka 集群中，每个节点都有一个唯一的 ID
      KAFKA_NODE_ID: 1
      # 指定这个 Kafka 节点的角色为 broker（消息代理）和 controller（控制器）。Controller 负责管理集群中的分区分配等任务
      KAFKA_PROCESS_ROLES: broker,controller
      # 设置 Kafka 的监听器。这里配置了两种监听器，一种是普通的 PLAINTEXT 监听器在 9092 端口，用于接收客户端的连接；另一种是 CONTROLLER 监听器在 9093 端口，用于控制器的通信
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      # 设置对外公布的监听器地址，这里表示客户端可以通过 “[localhost:9092](https://localhost:9092/)” 连接到这个 Kafka 节点，如果不配置外部无法连接到Kafka，服务器请设置为外网ip
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # 指定控制器使用的监听器名称为 “CONTROLLER”
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # 定义监听器的安全协议映射。这里表示 CONTROLLER 监听器使用 PLAINTEXT 协议，普通的 PLAINTEXT 监听器也使用 PLAINTEXT 协议
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 设置控制器的法定人数投票者，这里表示只有一个节点（ID 为 1）在 “[localhost:9093](https://localhost:9093/)” 作为投票者
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # 设置 Kafka 的Topic偏移量（用于记录消费者的消费位置）的复制因子为 1，即只有一个副本，最小1，最大不能超过节点数
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # 设置 Kafka 的事务状态日志的复制因子为 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # 设置事务状态日志的最小同步副本数为 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # 设置消费者组的初始重新平衡延迟为 0 毫秒
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # 设置默认的主题分区数量为 3
      KAFKA_NUM_PARTITIONS: 3

networks:
  pub-network:
    driver: bridge


# from: https://blog.csdn.net/weixin_62799021/article/details/143242822

