solon.app:
    name: demoapp
    group: demo

solon.output.meta: 1

solon.logging.logger:
    "org.eclipse.jetty.*":
        level: "WARN"
    "com.zaxxer.hikari.*":
        level: "WARN"


mybatis-flex.datasource:
  db1:
    type: "com.zaxxer.hikari.HikariDataSource"
    jdbcUrl: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
    driverClassName: "org.h2.Driver"
  db2:
    type: "com.zaxxer.hikari.HikariDataSource"
    jdbcUrl: "jdbc:h2:mem:test2;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
    driverClassName: "org.h2.Driver"

#默认
mybatis-flex:
  defaultDatasourceKey: db1
  typeAliases:    #支持包名 或 类名
    - "demo4035.model"
  mappers:        #支持包名 或 类名 或 xml（.xml结尾 或 *.xml 结尾）
    - "demo4035.dso.mapper"
  configuration:
    cacheEnabled: false
    mapUnderscoreToCamelCase: true
  plugins:
    - test:
        class: "demo4035.dso.TestInterceptorImpl"

#分页组件的配置
sqlhelper:
    mybatis:
        instrumentor:
            dialect: "mysql"
            cache-instrumented-sql: true
            subquery-paging-start-flag: "[PAGING_StART]"
            subquery-paging-end-flag: "[PAGING_END]"
        pagination:
            count: true
            default-page-size: 10
            use-last-page-if-page-no-out: true
            count-suffix: _COUNT