/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example.demo.tutorial;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class tutorialConstants {

  /**
   * Thrift also lets you define constants for use across languages. Complex
   * types and structs are specified using JSON notation.
   */
  public static final int INT32CONSTANT = 9853;

  public static final java.util.Map<String, String> MAPCONSTANT = new java.util.HashMap<String, String>();
  static {
    MAPCONSTANT.put("goodnight", "moon");
    MAPCONSTANT.put("hello", "world");
  }

}
