server.port: 8011

dubbo:
  application:
    name: hello
    owner: noear
    logger: slf4j
  registry:
    address: zookeeper://localhost:2181


# 记录器级别的配置示例
solon.logging:
  appender:
    file:
      enable: false
  logger:
    "root": #默认记录器配置
      level: INFO