solon.logging.logger:
  root:
    level: INFO

solon.ai.chat:
  deepseek:
    apiUrl: "http://127.0.0.1:11434/api/chat" # 使用完整地址（而不是 api_base）
    provider: "ollama"
    model: "deepseek-r1:7b"
    timeout: "300s"

solon.ai.repo:
  websearch:
    apiUrl: "https://api.bochaai.com/v1/web-search" # 使用完整地址（而不是 api_base）
    apiKey: "sk-5d36eae2c4a54e2596c7625d9888a9d8"

solon.ai.embed:
  bgem3:
    apiUrl: "http://127.0.0.1:11434/api/embed" # 使用完整地址（而不是 api_base）
    provider: "ollama" # 使用 ollama 服务时，需要配置 provider
    model: "bge-m3:latest"