server.port: 8082

solon.app:
  name: docapi
  group: demo


knife4j.enable: true
knife4j.production: false
knife4j.basic.enable: true
knife4j.basic.username: admin
knife4j.basic.password: 123456
knife4j.setting.enableOpenApi: false
knife4j.setting.enableSwaggerModels: true
knife4j.setting.enableFooter: false
knife4j.setting.enableFooterCustom: true
knife4j.setting.footerCustomContent: Apache License 2.0 | Copyright 2022-[SNOWY](https://www.xiaonuo.vip)

solon.cloud.nacos:
  server: "localhost:8848"           #nacos2 服务地址

solon.docs:
  discover:
    enabled: true
    uriPattern: "swagger/v2?group=adminApi"
    syncStatus: true
    excluded-services:
      - "docapi"
  routes:
    - id: bizDocApi
      groupName: "业务功能BIZ"
      basicAuth:
        admin: 123456
      upstream:
        target: "http://localhost:82/"
        contextPath: "/snowy-solon"
        uri: "swagger/v2?group=bizDocApi"
    - id: sysDocApi
      groupName: "系统功能SYS"
      basicAuth:
        admin: 123456
      upstream:
        target: "http://localhost:82/"
        contextPath: "/snowy-solon"
        uri: "swagger/v2?group=sysDocApi"

solon.cloud.gateway:
  discover:
    enabled: true
  routes:
    - id: slef
      target: "http://localhost:8082" # 或 "lb://user-service"
      predicates:
        - "Path=/slef/**"
    - id: snowy-solon
      target: "http://localhost:82"
      predicates:
        - "Path=/snowy-solon/**"
  default-filters:
    - "StripPrefix=1"
