solon.app:
  name: demoapp
  group: demo

solon.output.meta: 1

test:
  db1:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  db2:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#下面这些，不需要
#beetlsql: sqlManager1
#beetlsql.sqlManager1.ds: ds1
#beetlsql.sqlManager1.basePackage: org.beetl.sql.springboot.simple
#beetlsql.sqlManager1.dbStyle: org.beetl.sql.core.db.MySqlStyle




#sms:
#  master:
#    schema: rock
#    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#  slave:
#    schema: rock
#    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
