server:
  port: 6969

solon.dataSources:
  db1!:
    class: "com.zaxxer.hikari.HikariDataSource"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jdbcUrl: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=1000
  db2:
    class: "com.zaxxer.hikari.HikariDataSource"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jdbcUrl: jdbc:h2:file:./test.db;DB_CLOSE_DELAY=1000

demo1.cache:
  driverType: "redis" #驱动类型
  keyHeader: "demo" #默认为 ${solon.app.name} ，可不配置
  defSeconds: 30 #默认为 30，可不配置
  server: "localhost:6379"
  db: 0 #默认为 0，可不配置
  password: "123456"
  maxTotaol: 200 #默认为 200，可不配