server.port: 9905

solon.app:
  group: SEATA_GROUP
  name: remote

solon.dataSources:
  db1!:
    class: "com.alibaba.druid.pool.DruidDataSource"
    jdbcUrl: jdbc:mysql://localhost:3306/solon-seata-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

solon.logging.appender:
  console:
    level: TRACE

# 记录器级别的配置示例
solon.logging.logger:
  "root": #默认记录器配置
    level: TRACE
  "org.apache.seata.config.FileConfiguration":
    level: INFO
  "org.apache.seata.core.rpc.processor.client.ClientHeartbeatProcessor":
    level: INFO
  "org.apache.seata.core.rpc.netty.AbstractNettyRemoting":
    level: INFO
  "com.alibaba.nacos":
    level: INFO

seata:
  applicationId: remote
  txServiceGroup: default_tx_group
  enableAutoDataSourceProxy: true  # 确保自动代理数据源
  service:
    vgroupMapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091  # Seata TC 服务器地址
  config:
    type: file
  registry:
    type: file