
#for mysql
#db1.schema: rock
#db1.jdbcUrl: jdbc:mysql://localdb:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#db1.driverClassName: com.mysql.jdbc.Driver
#db1.username: demo
#db1.password: UL0hHlg0Ybq60xyb

#for h2
db1.jdbcUrl: jdbc:h2:~/localjt;MODE=MYSQL;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
db1.driverClassName: org.h2.Driver
db1.username: sa
db1.password: Ca78XJDFawZ5jaOL


solon.logging:
  appender:
    console:
      level: INFO
  logger:
    "net.hasor":
      level: WARN
    "org.eclipse":
      level: WARN
    "com.zaxxer.hikari":
      level: WARN


solon.extend: "!dway_ext"

#hasor
HASOR_DATAQL_DATAWAY: true
HASOR_DATAQL_DATAWAY_ADMIN: true