
solon.app:
  name: "demo-app"
  group: "demo"

solon.logging:
  logger:
    root:
      level: INFO

# 配置可以自由定义，与 @Bean 代码对应起来即可（以下为参考）
solon.rocketmq:
  properties:  #公共配置（配置项，参考：ClientConfigurationBuilder）
    endpoints: "127.0.0.1:8081"
    sessionCredentialsProvider:
      "@type": "demoB002.SessionCredentialsProviderImpl" # solon 支持 "@type" 类型申明当前实例数据
      accessKey: "xxx"
      accessSecret: "xxx"
      securityToken: "xxx"
    requestTimeout: "10s"
  producer: #生产者专属配置（配置项，参考：ProducerBuilder）
    maxAttempts: 3
  consumer: #消费者专属配置（配置项，参考：PushConsumerBuilder）
    consumerGroup: "${solon.app.group}_${solon.app.name}"
    consumptionThreadCount: 2
    maxCacheMessageCount: 1
    maxCacheMessageSizeInBytes: 1
