solon.app:
    name: demoapp
    group: demo

solon.output.meta: 1

test.db1:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#映射配置
mybatis.db1:
    typeAliases:    #支持包名 或 类名（.class 结尾）
        - "demo4023.model"
    mappers:        #支持包名 或 类名（.class 结尾）或 xml（.xml结尾）
        - "demo4023.dso.mapper"

#mybatis.plugin:
#    - pagehelper:
#        class: com.github.pagehelper.PageHelper
#        dialect: mysql
#        rowBoundsWithCount: true


#分页组件的配置
pagehelper:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    pageSizeZero: true
    reasonable: false
    params: pageNum=pageHelperStart;pageSize=pageHelperRows;
    supportMethodsArguments: false